// Joker data for Balarodle
// ability: 0=+Mult, 1=+Chips, 2=+Mult+Chips, 3=xMult, 4=Economy, 5=Creation, 6=Retrigger/Copy, 7=Hands/Discards, 8=Other
// scaling: gains power over time
// rng: has listed probability (e.g. "1 in X chance")

const ABILITY_LABELS = ['+Mult', '+Chips', '+Mult +Chips', 'xMult', 'Economy', 'Creation', 'Retrigger/Copy', 'Hands/Discards', 'Other'];

const ALL_JOKERS = [
    // ── Common ──
    { name: 'Joker',                 rarity: 'Common',    cost: 2,  ability: 0, scaling: false, rng: false },
    { name: 'Greedy Joker',          rarity: 'Common',    cost: 5,  ability: 0, scaling: false, rng: false },
    { name: 'Lusty Joker',           rarity: 'Common',    cost: 5,  ability: 0, scaling: false, rng: false },
    { name: 'Wrathful Joker',        rarity: 'Common',    cost: 5,  ability: 0, scaling: false, rng: false },
    { name: 'Gluttonous Joker',      rarity: 'Common',    cost: 5,  ability: 0, scaling: false, rng: false },
    { name: 'Jolly Joker',           rarity: 'Common',    cost: 3,  ability: 0, scaling: false, rng: false },
    { name: 'Zany Joker',            rarity: 'Common',    cost: 4,  ability: 0, scaling: false, rng: false },
    { name: 'Mad Joker',             rarity: 'Common',    cost: 4,  ability: 0, scaling: false, rng: false },
    { name: 'Crazy Joker',           rarity: 'Common',    cost: 4,  ability: 0, scaling: false, rng: false },
    { name: 'Droll Joker',           rarity: 'Common',    cost: 4,  ability: 0, scaling: false, rng: false },
    { name: 'Sly Joker',             rarity: 'Common',    cost: 3,  ability: 1, scaling: false, rng: false },
    { name: 'Wily Joker',            rarity: 'Common',    cost: 4,  ability: 1, scaling: false, rng: false },
    { name: 'Clever Joker',          rarity: 'Common',    cost: 4,  ability: 1, scaling: false, rng: false },
    { name: 'Devious Joker',         rarity: 'Common',    cost: 4,  ability: 1, scaling: false, rng: false },
    { name: 'Crafty Joker',          rarity: 'Common',    cost: 4,  ability: 1, scaling: false, rng: false },
    { name: 'Half Joker',            rarity: 'Common',    cost: 5,  ability: 0, scaling: false, rng: false },
    { name: 'Credit Card',           rarity: 'Common',    cost: 1,  ability: 4, scaling: false, rng: false },
    { name: 'Banner',                rarity: 'Common',    cost: 5,  ability: 1, scaling: false, rng: false },
    { name: 'Mystic Summit',         rarity: 'Common',    cost: 5,  ability: 0, scaling: false, rng: false },
    { name: 'Misprint',              rarity: 'Common',    cost: 4,  ability: 0, scaling: false, rng: false },
    { name: 'Raised Fist',           rarity: 'Common',    cost: 5,  ability: 0, scaling: false, rng: false },
    { name: 'Chaos the Clown',       rarity: 'Common',    cost: 4,  ability: 4, scaling: false, rng: false },
    { name: 'Scary Face',            rarity: 'Common',    cost: 4,  ability: 1, scaling: false, rng: false },
    { name: 'Abstract Joker',        rarity: 'Common',    cost: 4,  ability: 0, scaling: false, rng: false },
    { name: 'Delayed Gratification', rarity: 'Common',    cost: 4,  ability: 4, scaling: false, rng: false },
    { name: 'Gros Michel',           rarity: 'Common',    cost: 5,  ability: 0, scaling: false, rng: true  },
    { name: 'Even Steven',           rarity: 'Common',    cost: 4,  ability: 0, scaling: false, rng: false },
    { name: 'Odd Todd',              rarity: 'Common',    cost: 4,  ability: 1, scaling: false, rng: false },
    { name: 'Scholar',               rarity: 'Common',    cost: 4,  ability: 2, scaling: false, rng: false },
    { name: 'Business Card',         rarity: 'Common',    cost: 4,  ability: 4, scaling: false, rng: true  },
    { name: 'Supernova',             rarity: 'Common',    cost: 5,  ability: 0, scaling: false, rng: false },
    { name: 'Ride the Bus',          rarity: 'Common',    cost: 6,  ability: 0, scaling: true,  rng: false },
    { name: 'Egg',                   rarity: 'Common',    cost: 4,  ability: 4, scaling: true,  rng: false },
    { name: 'Faceless Joker',        rarity: 'Common',    cost: 4,  ability: 4, scaling: false, rng: false },
    { name: 'Green Joker',           rarity: 'Common',    cost: 4,  ability: 0, scaling: true,  rng: false },
    { name: 'Superposition',         rarity: 'Common',    cost: 4,  ability: 5, scaling: false, rng: false },
    { name: 'To Do List',            rarity: 'Common',    cost: 4,  ability: 4, scaling: false, rng: false },
    { name: 'Cavendish',             rarity: 'Common',    cost: 4,  ability: 3, scaling: false, rng: true  },
    { name: 'Red Card',              rarity: 'Common',    cost: 5,  ability: 0, scaling: true,  rng: false },
    { name: 'Square Joker',          rarity: 'Common',    cost: 4,  ability: 1, scaling: true,  rng: false },
    { name: 'Riff-Raff',             rarity: 'Common',    cost: 6,  ability: 5, scaling: false, rng: false },
    { name: 'Blue Joker',            rarity: 'Common',    cost: 5,  ability: 1, scaling: false, rng: false },
    { name: 'Splash',                rarity: 'Common',    cost: 3,  ability: 8, scaling: false, rng: false },
    { name: 'Walkie Talkie',         rarity: 'Common',    cost: 4,  ability: 2, scaling: false, rng: false },
    { name: 'Smiley Face',           rarity: 'Common',    cost: 4,  ability: 0, scaling: false, rng: false },
    { name: 'Popcorn',               rarity: 'Common',    cost: 5,  ability: 0, scaling: false, rng: false },
    { name: 'Reserved Parking',      rarity: 'Common',    cost: 6,  ability: 4, scaling: false, rng: true  },
    { name: 'Mail-In Rebate',        rarity: 'Common',    cost: 4,  ability: 4, scaling: false, rng: false },
    { name: 'Hallucination',         rarity: 'Common',    cost: 4,  ability: 5, scaling: false, rng: true  },
    { name: 'Fortune Teller',        rarity: 'Common',    cost: 6,  ability: 0, scaling: true,  rng: false },
    { name: 'Juggler',               rarity: 'Common',    cost: 4,  ability: 7, scaling: false, rng: false },
    { name: 'Drunkard',              rarity: 'Common',    cost: 4,  ability: 7, scaling: false, rng: false },
    { name: 'Golden Joker',          rarity: 'Common',    cost: 6,  ability: 4, scaling: false, rng: false },
    { name: 'Golden Ticket',         rarity: 'Common',    cost: 5,  ability: 4, scaling: false, rng: false },
    { name: 'Swashbuckler',          rarity: 'Common',    cost: 4,  ability: 0, scaling: false, rng: false },
    { name: 'Shoot the Moon',        rarity: 'Common',    cost: 5,  ability: 0, scaling: false, rng: false },
    { name: 'Hanging Chad',          rarity: 'Common',    cost: 4,  ability: 6, scaling: false, rng: false },
    { name: 'Photograph',            rarity: 'Common',    cost: 5,  ability: 3, scaling: false, rng: false },

    // ── Uncommon ──
    { name: 'Joker Stencil',         rarity: 'Uncommon',  cost: 8,  ability: 3, scaling: false, rng: false },
    { name: 'Four Fingers',          rarity: 'Uncommon',  cost: 7,  ability: 8, scaling: false, rng: false },
    { name: 'Mime',                  rarity: 'Uncommon',  cost: 5,  ability: 6, scaling: false, rng: false },
    { name: 'Ceremonial Dagger',     rarity: 'Uncommon',  cost: 6,  ability: 0, scaling: true,  rng: false },
    { name: 'Marble Joker',          rarity: 'Uncommon',  cost: 6,  ability: 5, scaling: false, rng: false },
    { name: 'Loyalty Card',          rarity: 'Uncommon',  cost: 5,  ability: 3, scaling: false, rng: false },
    { name: '8 Ball',                rarity: 'Uncommon',  cost: 5,  ability: 5, scaling: false, rng: true  },
    { name: 'Dusk',                  rarity: 'Uncommon',  cost: 5,  ability: 6, scaling: false, rng: false },
    { name: 'Fibonacci',             rarity: 'Uncommon',  cost: 8,  ability: 0, scaling: false, rng: false },
    { name: 'Steel Joker',           rarity: 'Uncommon',  cost: 7,  ability: 3, scaling: false, rng: false },
    { name: 'Hack',                  rarity: 'Uncommon',  cost: 6,  ability: 6, scaling: false, rng: false },
    { name: 'Blackboard',            rarity: 'Uncommon',  cost: 6,  ability: 3, scaling: false, rng: false },
    { name: 'Constellation',         rarity: 'Uncommon',  cost: 6,  ability: 3, scaling: true,  rng: false },
    { name: 'Hiker',                 rarity: 'Uncommon',  cost: 5,  ability: 1, scaling: true,  rng: false },
    { name: 'Sixth Sense',           rarity: 'Uncommon',  cost: 6,  ability: 5, scaling: false, rng: false },
    { name: 'Burglar',               rarity: 'Uncommon',  cost: 6,  ability: 7, scaling: false, rng: false },
    { name: 'Pareidolia',            rarity: 'Uncommon',  cost: 5,  ability: 8, scaling: false, rng: false },
    { name: 'Space Joker',           rarity: 'Uncommon',  cost: 5,  ability: 8, scaling: false, rng: true  },
    { name: 'Runner',                rarity: 'Uncommon',  cost: 5,  ability: 1, scaling: true,  rng: false },
    { name: 'Ice Cream',             rarity: 'Uncommon',  cost: 5,  ability: 1, scaling: false, rng: false },
    { name: 'Midas Mask',            rarity: 'Uncommon',  cost: 7,  ability: 8, scaling: false, rng: false },
    { name: 'Luchador',              rarity: 'Uncommon',  cost: 5,  ability: 8, scaling: false, rng: false },
    { name: 'Card Sharp',            rarity: 'Uncommon',  cost: 6,  ability: 3, scaling: false, rng: false },
    { name: 'Madness',               rarity: 'Uncommon',  cost: 7,  ability: 0, scaling: true,  rng: false },
    { name: 'Hologram',              rarity: 'Uncommon',  cost: 7,  ability: 0, scaling: true,  rng: false },
    { name: 'Cloud 9',               rarity: 'Uncommon',  cost: 7,  ability: 4, scaling: false, rng: false },
    { name: 'Rocket',                rarity: 'Uncommon',  cost: 6,  ability: 4, scaling: true,  rng: false },
    { name: 'Gift Card',             rarity: 'Uncommon',  cost: 6,  ability: 4, scaling: false, rng: false },
    { name: 'Turtle Bean',           rarity: 'Uncommon',  cost: 6,  ability: 7, scaling: false, rng: false },
    { name: 'Erosion',               rarity: 'Uncommon',  cost: 6,  ability: 0, scaling: false, rng: false },
    { name: 'Astronomer',            rarity: 'Uncommon',  cost: 8,  ability: 4, scaling: false, rng: false },
    { name: 'Bull',                  rarity: 'Uncommon',  cost: 6,  ability: 1, scaling: false, rng: false },
    { name: 'Diet Cola',             rarity: 'Uncommon',  cost: 6,  ability: 5, scaling: false, rng: false },
    { name: 'Trading Card',          rarity: 'Uncommon',  cost: 6,  ability: 4, scaling: false, rng: false },
    { name: 'Flash Card',            rarity: 'Uncommon',  cost: 5,  ability: 0, scaling: true,  rng: false },
    { name: 'Spare Trousers',        rarity: 'Uncommon',  cost: 6,  ability: 0, scaling: true,  rng: false },
    { name: 'Ramen',                 rarity: 'Uncommon',  cost: 6,  ability: 3, scaling: false, rng: false },
    { name: 'Seltzer',               rarity: 'Uncommon',  cost: 6,  ability: 6, scaling: false, rng: false },
    { name: 'Castle',                rarity: 'Uncommon',  cost: 6,  ability: 1, scaling: true,  rng: false },
    { name: 'Shortcut',              rarity: 'Uncommon',  cost: 7,  ability: 8, scaling: false, rng: false },
    { name: 'Vampire',               rarity: 'Uncommon',  cost: 7,  ability: 3, scaling: true,  rng: false },
    { name: 'To the Moon',           rarity: 'Uncommon',  cost: 5,  ability: 4, scaling: false, rng: false },
    { name: 'Lucky Cat',             rarity: 'Uncommon',  cost: 6,  ability: 0, scaling: true,  rng: true  },
    { name: 'Séance',                rarity: 'Uncommon',  cost: 6,  ability: 5, scaling: false, rng: false },
    { name: 'Smeared Joker',         rarity: 'Uncommon',  cost: 7,  ability: 8, scaling: false, rng: false },
    { name: 'Throwback',             rarity: 'Uncommon',  cost: 6,  ability: 3, scaling: true,  rng: false },
    { name: 'Rough Gem',             rarity: 'Uncommon',  cost: 7,  ability: 4, scaling: false, rng: false },
    { name: 'Bloodstone',            rarity: 'Uncommon',  cost: 7,  ability: 3, scaling: false, rng: true  },
    { name: 'Arrowhead',             rarity: 'Uncommon',  cost: 7,  ability: 1, scaling: false, rng: false },
    { name: 'Onyx Agate',            rarity: 'Uncommon',  cost: 7,  ability: 0, scaling: false, rng: false },
    { name: 'Glass Joker',           rarity: 'Uncommon',  cost: 6,  ability: 3, scaling: true,  rng: false },
    { name: 'Showman',               rarity: 'Uncommon',  cost: 5,  ability: 8, scaling: false, rng: false },
    { name: 'Flower Pot',            rarity: 'Uncommon',  cost: 6,  ability: 3, scaling: false, rng: false },
    { name: 'Stone Joker',           rarity: 'Uncommon',  cost: 6,  ability: 1, scaling: false, rng: false },
    { name: 'Merry Andy',            rarity: 'Uncommon',  cost: 7,  ability: 7, scaling: false, rng: false },
    { name: "Oops! All 6s",          rarity: 'Uncommon',  cost: 4,  ability: 8, scaling: false, rng: false },
    { name: 'The Idol',              rarity: 'Uncommon',  cost: 6,  ability: 3, scaling: false, rng: false },
    { name: 'Seeing Double',         rarity: 'Uncommon',  cost: 6,  ability: 3, scaling: false, rng: false },
    { name: 'Matador',               rarity: 'Uncommon',  cost: 7,  ability: 4, scaling: false, rng: false },
    { name: 'Satellite',             rarity: 'Uncommon',  cost: 6,  ability: 4, scaling: false, rng: false },
    { name: 'Cartomancer',           rarity: 'Uncommon',  cost: 6,  ability: 5, scaling: false, rng: false },
    { name: 'Bootstraps',            rarity: 'Uncommon',  cost: 7,  ability: 0, scaling: false, rng: false },

    // ── Rare ──
    { name: 'DNA',                   rarity: 'Rare',      cost: 8,  ability: 8, scaling: false, rng: false },
    { name: 'Vagabond',              rarity: 'Rare',      cost: 8,  ability: 5, scaling: false, rng: false },
    { name: 'Baron',                 rarity: 'Rare',      cost: 8,  ability: 3, scaling: false, rng: false },
    { name: 'Ancient Joker',         rarity: 'Rare',      cost: 8,  ability: 3, scaling: false, rng: false },
    { name: 'Baseball Card',         rarity: 'Rare',      cost: 8,  ability: 3, scaling: false, rng: false },
    { name: 'Campfire',              rarity: 'Rare',      cost: 9,  ability: 3, scaling: true,  rng: false },
    { name: 'Blueprint',             rarity: 'Rare',      cost: 10, ability: 6, scaling: false, rng: false },
    { name: 'Wee Joker',             rarity: 'Rare',      cost: 8,  ability: 1, scaling: true,  rng: false },
    { name: 'Hit the Road',          rarity: 'Rare',      cost: 8,  ability: 3, scaling: true,  rng: false },
    { name: 'The Duo',               rarity: 'Rare',      cost: 8,  ability: 3, scaling: false, rng: false },
    { name: 'The Trio',              rarity: 'Rare',      cost: 8,  ability: 3, scaling: false, rng: false },
    { name: 'The Family',            rarity: 'Rare',      cost: 8,  ability: 3, scaling: false, rng: false },
    { name: 'The Order',             rarity: 'Rare',      cost: 8,  ability: 3, scaling: false, rng: false },
    { name: 'The Tribe',             rarity: 'Rare',      cost: 8,  ability: 3, scaling: false, rng: false },
    { name: 'Stuntman',              rarity: 'Rare',      cost: 7,  ability: 1, scaling: false, rng: false },
    { name: 'Invisible Joker',       rarity: 'Rare',      cost: 8,  ability: 5, scaling: false, rng: false },
    { name: 'Brainstorm',            rarity: 'Rare',      cost: 10, ability: 6, scaling: false, rng: false },
    { name: "Driver's License",      rarity: 'Rare',      cost: 7,  ability: 3, scaling: false, rng: false },
    { name: 'Burnt Joker',           rarity: 'Rare',      cost: 8,  ability: 8, scaling: false, rng: false },
    { name: 'Obelisk',               rarity: 'Rare',      cost: 8,  ability: 3, scaling: true,  rng: false },
    { name: 'Mr. Bones',             rarity: 'Rare',      cost: 5,  ability: 8, scaling: false, rng: false },
    { name: 'Acrobat',               rarity: 'Rare',      cost: 6,  ability: 3, scaling: false, rng: false },
    { name: 'Sock and Buskin',       rarity: 'Rare',      cost: 6,  ability: 6, scaling: false, rng: false },
    { name: 'Troubadour',            rarity: 'Rare',      cost: 6,  ability: 7, scaling: false, rng: false },
    { name: 'Certificate',           rarity: 'Rare',      cost: 6,  ability: 5, scaling: false, rng: false },

    // ── Legendary ──
    { name: 'Triboulet',             rarity: 'Legendary', cost: 20, ability: 3, scaling: false, rng: false },
    { name: 'Canio',                 rarity: 'Legendary', cost: 20, ability: 3, scaling: true,  rng: false },
    { name: 'Yorick',                rarity: 'Legendary', cost: 20, ability: 3, scaling: true,  rng: false },
    { name: 'Chicot',                rarity: 'Legendary', cost: 20, ability: 8, scaling: false, rng: false },
    { name: 'Perkeo',                rarity: 'Legendary', cost: 20, ability: 5, scaling: false, rng: false },
];
